#pragma config(Sensor, dgtl1,  rightQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  stahp,          sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//moves forward 1 foot, approx.
void moveForward(){

	moveStraightForRotations(1.7, rightQuad, leftQuad);

}

void moveForwardHalf(){

	moveStraightForRotations(.85, rightQuad, leftQuad);

}

void moveForwardThreeFour(){

	moveStraightForRotations(1.275, rightQuad, leftQuad);

}

//moves backward 1 foot, approx.
void moveBackward(){

	moveStraightForRotations(-1.7, rightQuad, leftQuad);

}

void turnLeft(){

	//Our machine requires that the direction be opposite from the one you want to go. Don't ask, it just works. 
	//Or submit a pull request if you know how to fix it! #github
	pointTurn(right, 63);
	untilRotations(1.6, leftQuad);

}

void turnRight(){

	//Our machine requires that the direction be opposite from the one you want to go. Don't ask, it just works. 
	//Or submit a pull request if you know how to fix it! #github
	pointTurn(left, 63);
	untilRotations(1.7, rightQuad);

}
// this (in theory) stops the motors. However, stopAllTasks might work better.
void stahpAllMotors(){
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}

task Drive()
{

	//use the above functions to navigate your maze.
	moveForward();
	moveForward();
	turnLeft();
	moveForward();
	moveForward();
	turnLeft();
	moveForward();
	turnRight();
	moveForward();
	turnRight();
	moveForward();
	moveForward();
	turnRight();
	moveForward();
	moveForward();

}

int buttonCount(){
	int btnCount = 0;
	if(SensorValue[stahp] == 1){
		btnCount = btnCount+1;
	}
	else{}
	return btnCount;
}

//this starts and stops the navigation.
task main(){


 while(1==1){
 	if(buttonCount % 2 != 0){
 		startTask(Drive);
 	}
 	else{
 		stopTask(Drive);
 	}
 }
}


/*
###############################################################
#							Happy holidays, everyone! I'm done							#
#		working on this. It's yours. Do what you want with this. 	#
#   																													#
#																															#
#																										Thanks,		#
#																															#
#																										Charlie		#
#																															#
#															/\															#
#														 /##\ 												 		#
#														/####\														#
#													 /######\														#
#											 		/########\													#
#												 /##########\													#
#												/############\												#
#											 /##############\												#
#											/################\											#
#														 |##|															#
###############################################################
*/


/*
###############################################################
#   																													#
#   From												To:														#
#		19071 Bockalocka Drive			GitHub												#
#		Portland, OR 97045																			 	#
#   Charlie Welsh																							#
#																															#
#																															#
#																															#
#																															#
#																															#
#															/\															#
#														 /##\ 												 		#
#														/####\														#
#													 /######\														#
#											 		/########\													#
#												 /##########\													#
#												/############\												#
#											 /##############\												#
#											/################\											#
#														 |##|															#
###############################################################
*/
