#pragma config(Sensor, dgtl1,  rightQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  stahp,          sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//moves forward 1 foot, approx.
void moveForward(){

	startMotor(leftMotor, 63);
	startMotor(rightMotor, 63);
	untilRotations(1.75, leftQuad);
	stopMotor(leftMotor);
	stopMotor(rightMotor);

}

void moveForwardHalf(){

	startMotor(leftMotor, 63);
	startMotor(rightMotor, 63);
	untilRotations(.875, leftQuad);
	stopMotor(leftMotor);
	stopMotor(rightMotor);

}

void moveForwardThreeFour(){

	startMotor(leftMotor, 63);
	startMotor(rightMotor, 63);
	untilRotations(1.3125, leftQuad);
	stopMotor(leftMotor);
	stopMotor(rightMotor);

}

//moves backward 1 foot, approx.
void moveBackward(){

	startMotor(leftMotor, -63);
	startMotor(rightMotor, -63);
	untilRotations(1.75, leftQuad);
	untilRotations(1.75, rightQuad);
	stopMotor(leftMotor);
	stopMotor(rightMotor);

}

void turnLeft(){

	startMotor(leftMotor, -100);
	startMotor(rightMotor, 127);
	untilRotations(1.15, leftQuad);
	untilRotations(1.15, rightQuad);
	stopMotor(leftMotor);
	stopMotor(rightMotor);

}

void turnRight(){

	startMotor(leftMotor, 127);
	startMotor(rightMotor,-100);
	untilRotations(1.15, leftQuad);
	untilRotations(1.15, rightQuad);
	stopMotor(leftMotor);
	stopMotor(rightMotor);

}

void stahpAllMotors(){
	stopMotor(leftMotor);
	stopMotor(rightMotor);	
}

task main()
{

	//use the above functions to navigate your maze.
	if(SensorValue[stahp] == 1){
		stopAllTasks();	
	}
	else{
		moveForward();
		moveForwardHalf();
		turnLeft();
		moveForwardHalf();
		turnLeft();
		wait(2);
		turnLeft();
	}

}
