#pragma config(Sensor, dgtl1,  rightQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  stahp,          sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//moves forward 1 foot, approx.
void moveForward(){

    moveStraightForRotations(1.7, rightQuad, leftQuad);

}

void moveForwardHalf(){

    moveStraightForRotations(.85, rightQuad, leftQuad);

}

void moveForwardThreeFour(){

    moveStraightForRotations(1.275, rightQuad, leftQuad);

}

//moves backward 1 foot, approx.
void moveBackward(){

    moveStraightForRotations(-1.7, rightQuad, leftQuad);

}

void turnLeft(){

    startMotor(leftMotor, 100);
    startMotor(rightMotor, -127);
    untilRotations(2.3, rightQuad);
    stopMotor(leftMotor);
    stopMotor(rightMotor);

}

void turnRight(){

    startMotor(leftMotor, -127);
    startMotor(rightMotor, 100);
    untilRotations(2.3, leftQuad);
    stopMotor(leftMotor);
    stopMotor(rightMotor);

}
// this (in theory) stops the motors. However, stopAllTasks might work better.
void stahpAllMotors(){
    stopMotor(leftMotor);
    stopMotor(rightMotor);
}

task main()
{

    //use the above functions to navigate your maze.
		moveForward();
		moveForwardHalf();
		turnLeft();
		moveForwardThreeQuarters();
		turnLeft();
		moveForward();
		turnLeft();
		moveForward();
		turnRight();
		moveForward();
		turnRight();
		moveForward();
		moveForward();
		turnRight();
		moveForward();
		moveForward();

}
